# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 15831a4715c1c22f304579ba44b606886a59270817953530c32eb4ec1ee494714a36d8f85328be73f4fdf2e77eebf9e2342dee5c3872bc4f71225d23d58a4e7f

test:
  secret_key_base: 3e38db45d6310cdb048b4342c0f953bb5a230b7b96593f59a23f6ab3c682f829e1433879fbc6405341bf8ca6df6711d4902c7ada21680db9bcec253cc71098d0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
